### ISSUE TITLE
readme 需要更新aigc_zoo

### ISSUE THREAD

**Issue by magnificent1208** [ssbuild/chatglm2_finetuning#11]
pip install -U git+https://github.com/ssbuild/aigc_zoo.git
今天更新的代码，需要添加这个

**Comment by ssbuild** [comment]
是的， 也可以从这下载安装 https://pypi.org/project/aigc-zoo/#files

**Comment by magnificent1208** [comment]
data_processer.py
infer.py
data_utils.py

里面import 内容需要修改
from aigc_zoo.model_zoo.chatglm2.tokenization_chatglm import ChatGLMTokenizer
from aigc_zoo.model_zoo.chatglm2.chatglm_model import MyTransformer,LoraArguments,setup_model_profile, ChatGLMConfig

这几个相关函数的import都要修改下
