### ISSUE TITLE
多卡训练报错，麻烦看下

### ISSUE THREAD

**Issue by tjulh** [ssbuild/chatglm2_finetuning#22]
执行python train.py报错如下
RuntimeError: Expected all tensors to be on the same device, but found at least 
two devices, cuda:2 and cuda:1! (when checking argument for argument index in 
method wrapper__index_select)

**Comment by tjulh** [comment]
train_info_args = {
    'devices': [1,2],
    'data_backend': 'parquet',  #one of record lmdb arrow_stream ,arrow_file, parquet , 超大数据集可以使用 lmdb , 注 lmdb 存储空间比record大
    # 预训练模型路径 , 从0训练，则置空
    **train_model_config,

    'convert_onnx': False, # 转换onnx模型
    'do_train': True,
    'train_file':  [ './data/finetune_train_examples.json'],
    'max_epochs': 2,
    'max_steps': -1,
    'optimizer': 'lion', # one of [lamb,adma,adamw_hf,adamw,adamw_torch,adamw_torch_fused,adamw_torch_xla,adamw_apex_fused,adafactor,adamw_anyprecision,sgd,adagrad,adamw_bnb_8bit,adamw_8bit,lion_8bit,lion_32bit,paged_adamw_32bit,paged_adamw_8bit,paged_lion_32bit,paged_lion_8bit]

    'scheduler_type': 'CAWR', #one of [linear,WarmupCosine,CAWR,CAL,Step,ReduceLROnPlateau, cosine,cosine_with_restarts,polynomial,constant,constant_with_warmup,inverse_sqrt,reduce_lr_on_plateau]
    'scheduler':{'T_mult': 1,
                 'rewarm_epoch_num': 0.5,  # 如果 max_epochs is not None !
                 # 'T_0': 50000,    # 如果 max_epochs is None , 设定步数
                 'verbose': False},

    # 'scheduler_type': 'linear',# one of [linear,WarmupCosine,CAWR,CAL,Step,ReduceLROnPlateau
    # 'scheduler': None,

    # 切换scheduler类型
    # 'scheduler_type': 'WarmupCosine',
    # 'scheduler': None,

    # 'scheduler_type': 'ReduceLROnPlateau',
    # 'scheduler': None,

    # 'scheduler_type': 'Step',
    # 'scheduler':{ 'decay_rate': 0.999,'decay_steps': 100,'verbose': True},

    # 'scheduler_type': 'CAWR',
    # 'scheduler':{'T_mult': 1, 'rewarm_epoch_num': 2, 'verbose': True},

    # 'scheduler_type': 'CAL',
    # 'scheduler': {'rewarm_epoch_num': 2,'verbose': True},


    'optimizer_betas': (0.9, 0.999),
    'train_batch_size': 1,
    'eval_batch_size': 2,
    'test_batch_size': 2,
    'learning_rate': 2e-4,  #
    'adam_epsilon': 1e-8,
    'gradient_accumulation_steps': 1,
    'max_grad_norm': 1.0,
    'weight_decay': 0,
    'warmup_steps': 0,
    'output_dir': './output',
    'max_seq_length': 8, # 如果资源充足，推荐长度2048 与官方保持一致
    'max_target_length': 8,  # 预测最大长度, 保留字段
    'use_fast_tokenizer': False,
    'do_lower_case': False,

    ##############  lora模块
    #注意lora,adalora 和 ptuning-v2 禁止同时使用
   'lora': {**lora_info_args},
   'adalora': {**adalora_info_args},
}

**Comment by tjulh** [comment]
`# -*- coding: utf-8 -*-
# @Author  : ssbuild
# @Time    : 2023/5/31 14:43

import json
import os

# 模块配置， 默认启用lora
enable_deepspeed = True
enable_ptv2 = False
enable_lora = True
load_in_bit = 0  # 4 load_in_4bit, 8 load_in_8bit  other  0


if enable_lora:
    from config.sft_config_lora import *
elif enable_ptv2:
    from config.sft_config_ptv2 import *
else:
    from config.sft_config import *



if enable_lora:
    enable_ptv2 = False
    global_args['load_in_4bit'] = load_in_bit == 4
    global_args['load_in_8bit'] = load_in_bit == 8

    if global_args['load_in_4bit']:
        global_args['quantization_config'] = None

    #检查lora adalora是否开启
    if 'lora' not in train_info_args and 'adalora' not in train_info_args:
        raise ValueError('please config lora or adalora')
    if train_info_args.get('lora',{}).get('with_lora',False) and train_info_args.get('adalora',{}).get('with_lora',False):
        raise Exception('lora and adalora can set one at same time !')

    train_info_args.pop('prompt', None)
elif enable_ptv2:
    enable_lora = False
    global_args['load_in_4bit'] = False
    global_args['load_in_8bit'] = False
    train_info_args.pop('lora', None)
    train_info_args.pop('adalora', None)
else:
    enable_ptv2 = False
    enable_lora = False
    # global_args['load_in_4bit'] = False
    # global_args['load_in_8bit'] = False
    train_info_args.pop('lora',None)
    train_info_args.pop('adalora', None)
    train_info_args.pop('prompt', None)

#预处理
if 'rwkv' in train_info_args['tokenizer_name'].lower():
    train_info_args['use_fast_tokenizer'] = True


def get_deepspeed_config():
    '''
        lora prompt finetuning 使用 deepspeed_offload.json
        普通finetuning 使用deepspeed.json
    '''
    # 是否开启deepspeed
    if not enable_deepspeed:
        return None

    # 选择 deepspeed 配置文件
    is_need_update_config = False
    if enable_lora or enable_ptv2:
        is_need_update_config = True
        filename = os.path.join(os.path.dirname(__file__), 'deepspeed_offload.json')
    else:
        filename = os.path.join(os.path.dirname(__file__), 'deepspeed.json')


    with open(filename, mode='r', encoding='utf-8') as f:
        deepspeed_config = json.loads(f.read())

    #lora offload 同步优化器配置
    if is_need_update_config:
        optimizer = deepspeed_config.get('optimizer',None)
        if optimizer:
            optimizer['params']['betas'] = train_info_args.get('optimizer_betas', (0.9, 0.999))
            optimizer['params']['lr'] = train_info_args.get('learning_rate', 2e-5)
            optimizer['params']['eps'] = train_info_args.get('adam_epsilon', 1e-8)
    return deepspeed_config

`

**Comment by tjulh** [comment]
╭───────────────────── Traceback (most recent call last) ──────────────────────╮
│ /root/chatglm2_finetuning-dev/train.py:118 in <module>                       │
│                                                                              │
│   115 │   )                                                                  │
│   116 │                                                                      │
│   117 │   if train_datasets is not None:                                     │
│ ❱ 118 │   │   trainer.fit(pl_model, train_dataloaders=train_datasets)        │
│   119                                                                        │
│   120                                                                        │
│                                                                              │
│ /root/miniconda3/lib/python3.8/site-packages/lightning/pytorch/trainer/train │
│ er.py:531 in fit                                                             │
│                                                                              │
│    528 │   │   """                                                           │
│    529 │   │   model = _maybe_unwrap_optimized(model)                        │
│    530 │   │   self.strategy._lightning_module = model                       │
│ ❱  531 │   │   call._call_and_handle_interrupt(                              │
│    532 │   │   │   self, self._fit_impl, model, train_dataloaders, val_datal │
│    533 │   │   )                                                             │
│    534                                                                       │
│                                                                              │
│ /root/miniconda3/lib/python3.8/site-packages/lightning/pytorch/trainer/call. │
│ py:41 in _call_and_handle_interrupt                                          │
│                                                                              │
│    38 │   """                                                                │
│    39 │   try:                                                               │
│    40 │   │   if trainer.strategy.launcher is not None:                      │
│ ❱  41 │   │   │   return trainer.strategy.launcher.launch(trainer_fn, *args, │
│    42 │   │   return trainer_fn(*args, **kwargs)                             │
│    43 │                                                                      │
│    44 │   except _TunerExitException:                                        │
│                                                                              │
│ /root/miniconda3/lib/python3.8/site-packages/lightning/pytorch/strategies/la │
│ unchers/subprocess_script.py:91 in launch                                    │
│                                                                              │
│    88 │   │   """                                                            │
│    89 │   │   if not self.cluster_environment.creates_processes_externally:  │
│    90 │   │   │   self._call_children_scripts()                              │
│ ❱  91 │   │   return function(*args, **kwargs)                               │
│    92 │                                                                      │
│    93 │   def kill(self, signum: _SIGNUM) -> None:                           │
│    94 │   │   for proc in self.procs:                                        │
│                                                                              │
│ /root/miniconda3/lib/python3.8/site-packages/lightning/pytorch/trainer/train │
│ er.py:570 in _fit_impl                                                       │
│                                                                              │
│    567 │   │   │   model_provided=True,                                      │
│    568 │   │   │   model_connected=self.lightning_module is not None,        │
│    569 │   │   )                                                             │
│ ❱  570 │   │   self._run(model, ckpt_path=ckpt_path)                         │
│    571 │   │                                                                 │
│    572 │   │   assert self.state.stopped                                     │
│    573 │   │   self.training = False                                         │
│                                                                              │
│ /root/miniconda3/lib/python3.8/site-packages/lightning/pytorch/trainer/train │
│ er.py:975 in _run                                                            │
│                                                                              │
│    972 │   │   # ----------------------------                                │
│    973 │   │   # RUN THE TRAINER                                             │
│    974 │   │   # ----------------------------                                │
│ ❱  975 │   │   results = self._run_stage()                                   │
│    976 │   │                                                                 │
│    977 │   │   # ----------------------------                                │
│    978 │   │   # POST-Training CLEAN UP                                      │
│                                                                              │
│ /root/miniconda3/lib/python3.8/site-packages/lightning/pytorch/trainer/train │
│ er.py:1018 in _run_stage                                                     │
│                                                                              │
│   1015 │   │   │   with isolate_rng():                                       │
│   1016 │   │   │   │   self._run_sanity_check()                              │
│   1017 │   │   │   with torch.autograd.set_detect_anomaly(self._detect_anoma │
│ ❱ 1018 │   │   │   │   self.fit_loop.run()                                   │
│   1019 │   │   │   return None                                               │
│   1020 │   │   raise RuntimeError(f"Unexpected state {self.state}")          │
│   1021                                                                       │
│                                                                              │
│ /root/miniconda3/lib/python3.8/site-packages/lightning/pytorch/loops/fit_loo │
│ p.py:201 in run                                                              │
│                                                                              │
│   198 │   │   while not self.done:                                           │
│   199 │   │   │   try:                                                       │
│   200 │   │   │   │   self.on_advance_start()                                │
│ ❱ 201 │   │   │   │   self.advance()                                         │
│   202 │   │   │   │   self.on_advance_end()                                  │
│   203 │   │   │   │   self._restarting = False                               │
│   204 │   │   │   except StopIteration:                                      │
│                                                                              │
│ /root/miniconda3/lib/python3.8/site-packages/lightning/pytorch/loops/fit_loo │
│ p.py:354 in advance                                                          │
│                                                                              │
│   351 │   │   assert self._data_fetcher is not None                          │
│   352 │   │   self._data_fetcher.setup(combined_loader)                      │
│   353 │   │   with self.trainer.profiler.profile("run_training_epoch"):      │
│ ❱ 354 │   │   │   self.epoch_loop.run(self._data_fetcher)                    │
│   355 │                                                                      │
│   356 │   def on_advance_end(self) -> None:                                  │
│   357 │   │   trainer = self.trainer                                         │
│                                                                              │
│ /root/miniconda3/lib/python3.8/site-packages/lightning/pytorch/loops/trainin │
│ g_epoch_loop.py:133 in run                                                   │
│                                                                              │
│   130 │   │   self.on_run_start(data_fetcher)                                │
│   131 │   │   while not self.done:                                           │
│   132 │   │   │   try:                                                       │
│ ❱ 133 │   │   │   │   self.advance(data_fetcher)                             │
│   134 │   │   │   │   self.on_advance_end()                                  │
│   135 │   │   │   │   self._restarting = False                               │
│   136 │   │   │   except StopIteration:                                      │
│                                                                              │
│ /root/miniconda3/lib/python3.8/site-packages/lightning/pytorch/loops/trainin │
│ g_epoch_loop.py:218 in advance                                               │
│                                                                              │
│   215 │   │   │   with trainer.profiler.profile("run_training_batch"):       │
│   216 │   │   │   │   if trainer.lightning_module.automatic_optimization:    │
│   217 │   │   │   │   │   # in automatic optimization, there can only be one │
│ ❱ 218 │   │   │   │   │   batch_output = self.automatic_optimization.run(tra │
│   219 │   │   │   │   else:                                                  │
│   220 │   │   │   │   │   batch_output = self.manual_optimization.run(kwargs │
│   221                                                                        │
│                                                                              │
│ /root/miniconda3/lib/python3.8/site-packages/lightning/pytorch/loops/optimiz │
│ ation/automatic.py:185 in run                                                │
│                                                                              │
│   182 │   │   # ------------------------------                               │
│   183 │   │   # gradient update with accumulated gradients                   │
│   184 │   │   else:                                                          │
│ ❱ 185 │   │   │   self._optimizer_step(kwargs.get("batch_idx", 0), closure)  │
│   186 │   │                                                                  │
│   187 │   │   result = closure.consume_result()                              │
│   188 │   │   if result.loss is None:                                        │
│                                                                              │
│ /root/miniconda3/lib/python3.8/site-packages/lightning/pytorch/loops/optimiz │
│ ation/automatic.py:260 in _optimizer_step                                    │
│                                                                              │
│   257 │   │   │   self.optim_progress.optimizer.step.increment_ready()       │
│   258 │   │                                                                  │
│   259 │   │   # model hook                                                   │
│ ❱ 260 │   │   call._call_lightning_module_hook(                              │
│   261 │   │   │   trainer,                                                   │
│   262 │   │   │   "optimizer_step",                                          │
│   263 │   │   │   trainer.current_epoch,                                     │
│                                                                              │
│ /root/miniconda3/lib/python3.8/site-packages/lightning/pytorch/trainer/call. │
│ py:140 in _call_lightning_module_hook                                        │
│                                                                              │
│   137 │   pl_module._current_fx_name = hook_name                             │
│   138 │                                                                      │
│   139 │   with trainer.profiler.profile(f"[LightningModule]{pl_module.__clas │
│ ❱ 140 │   │   output = fn(*args, **kwargs)                                   │
│   141 │                                                                      │
│   142 │   # restore current_fx when nested context                           │
│   143 │   pl_module._current_fx_name = prev_fx_name                          │
│                                                                              │
│ /root/miniconda3/lib/python3.8/site-packages/lightning/pytorch/core/module.p │
│ y:1256 in optimizer_step                                                     │
│                                                                              │
│   1253 │   │   │   │   │   for pg in optimizer.param_groups:                 │
│   1254 │   │   │   │   │   │   pg["lr"] = lr_scale * self.learning_rate      │
│   1255 │   │   """                                                           │
│ ❱ 1256 │   │   optimizer.step(closure=optimizer_closure)                     │
│   1257 │                                                                     │
│   1258 │   def optimizer_zero_grad(self, epoch: int, batch_idx: int, optimiz │
│   1259 │   │   """Override this method to change the default behaviour of `` │
│                                                                              │
│ /root/miniconda3/lib/python3.8/site-packages/lightning/pytorch/core/optimize │
│ r.py:155 in step                                                             │
│                                                                              │
│   152 │   │   │   raise MisconfigurationException("When `optimizer.step(clos │
│   153 │   │                                                                  │
│   154 │   │   assert self._strategy is not None                              │
│ ❱ 155 │   │   step_output = self._strategy.optimizer_step(self._optimizer, c │
│   156 │   │                                                                  │
│   157 │   │   self._on_after_step()                                          │
│   158                                                                        │
│                                                                              │
│ /root/miniconda3/lib/python3.8/site-packages/lightning/pytorch/strategies/dd │
│ p.py:256 in optimizer_step                                                   │
│                                                                              │
│   253 │   │   │   model: reference to the model, optionally defining optimiz │
│   254 │   │   │   **kwargs: Any extra arguments to ``optimizer.step``        │
│   255 │   │   """                                                            │
│ ❱ 256 │   │   optimizer_output = super().optimizer_step(optimizer, closure,  │
│   257 │   │                                                                  │
│   258 │   │   if self._model_averager is None:                               │
│   259 │   │   │   return optimizer_output                                    │
│                                                                              │
│ /root/miniconda3/lib/python3.8/site-packages/lightning/pytorch/strategies/st │
│ rategy.py:225 in optimizer_step                                              │
│                                                                              │
│   222 │   │   model = model or self.lightning_module                         │
│   223 │   │   # TODO(fabric): remove assertion once strategy's optimizer_ste │
│   224 │   │   assert isinstance(model, pl.LightningModule)                   │
│ ❱ 225 │   │   return self.precision_plugin.optimizer_step(optimizer, model=m │
│   226 │                                                                      │
│   227 │   def _setup_model_and_optimizers(self, model: Module, optimizers: L │
│   228 │   │   """Setup a model and multiple optimizers together.             │
│                                                                              │
│ /root/miniconda3/lib/python3.8/site-packages/lightning/pytorch/plugins/preci │
│ sion/deepspeed.py:92 in optimizer_step                                       │
│                                                                              │
│    89 │   ) -> Any:                                                          │
│    90 │   │   if isinstance(optimizer, LBFGS):                               │
│    91 │   │   │   raise MisconfigurationException("DeepSpeed and the LBFGS o │
│ ❱  92 │   │   closure_result = closure()                                     │
│    93 │   │   self._after_closure(model, optimizer)                          │
│    94 │   │   skipped_backward = closure_result is None                      │
│    95 │   │   # in manual optimization, the closure does not return a value  │
│                                                                              │
│ /root/miniconda3/lib/python3.8/site-packages/lightning/pytorch/loops/optimiz │
│ ation/automatic.py:140 in __call__                                           │
│                                                                              │
│   137 │   │   return step_output                                             │
│   138 │                                                                      │
│   139 │   def __call__(self, *args: Any, **kwargs: Any) -> Optional[Tensor]: │
│ ❱ 140 │   │   self._result = self.closure(*args, **kwargs)                   │
│   141 │   │   return self._result.loss                                       │
│   142                                                                        │
│   143                                                                        │
│                                                                              │
│ /root/miniconda3/lib/python3.8/site-packages/lightning/pytorch/loops/optimiz │
│ ation/automatic.py:126 in closure                                            │
│                                                                              │
│   123 │   │   self._zero_grad_fn = zero_grad_fn                              │
│   124 │                                                                      │
│   125 │   def closure(self, *args: Any, **kwargs: Any) -> ClosureResult:     │
│ ❱ 126 │   │   step_output = self._step_fn()                                  │
│   127 │   │                                                                  │
│   128 │   │   if step_output.closure_loss is None:                           │
│   129 │   │   │   self.warning_cache.warn("`training_step` returned `None`.  │
│                                                                              │
│ /root/miniconda3/lib/python3.8/site-packages/lightning/pytorch/loops/optimiz │
│ ation/automatic.py:307 in _training_step                                     │
│                                                                              │
│   304 │   │   trainer = self.trainer                                         │
│   305 │   │                                                                  │
│   306 │   │   # manually capture logged metrics                              │
│ ❱ 307 │   │   training_step_output = call._call_strategy_hook(trainer, "trai │
│   308 │   │   self.trainer.strategy.post_training_step()                     │
│   309 │   │                                                                  │
│   310 │   │   return self.output_result_cls.from_training_step_output(traini │
│                                                                              │
│ /root/miniconda3/lib/python3.8/site-packages/lightning/pytorch/trainer/call. │
│ py:287 in _call_strategy_hook                                                │
│                                                                              │
│   284 │   │   return None                                                    │
│   285 │                                                                      │
│   286 │   with trainer.profiler.profile(f"[Strategy]{trainer.strategy.__clas │
│ ❱ 287 │   │   output = fn(*args, **kwargs)                                   │
│   288 │                                                                      │
│   289 │   # restore current_fx when nested context                           │
│   290 │   pl_module._current_fx_name = prev_fx_name                          │
│                                                                              │
│ /root/miniconda3/lib/python3.8/site-packages/lightning/pytorch/strategies/dd │
│ p.py:328 in training_step                                                    │
│                                                                              │
│   325 │   def training_step(self, *args: Any, **kwargs: Any) -> STEP_OUTPUT: │
│   326 │   │   assert self.model is not None                                  │
│   327 │   │   with self.precision_plugin.train_step_context():               │
│ ❱ 328 │   │   │   return self.model(*args, **kwargs)                         │
│   329 │                                                                      │
│   330 │   def validation_step(self, *args: Any, **kwargs: Any) -> Optional[S │
│   331 │   │   with self.precision_plugin.val_step_context():                 │
│                                                                              │
│ /root/miniconda3/lib/python3.8/site-packages/torch/nn/modules/module.py:1110 │
│ in _call_impl                                                                │
│                                                                              │
│   1107 │   │   # this function, and just call forward.                       │
│   1108 │   │   if not (self._backward_hooks or self._forward_hooks or self._ │
│   1109 │   │   │   │   or _global_forward_hooks or _global_forward_pre_hooks │
│ ❱ 1110 │   │   │   return forward_call(*input, **kwargs)                     │
│   1111 │   │   # Do not call functions when jit is used                      │
│   1112 │   │   full_backward_hooks, non_full_backward_hooks = [], []         │
│   1113 │   │   if self._backward_hooks or _global_backward_hooks:            │
│                                                                              │
│ /root/miniconda3/lib/python3.8/site-packages/deepspeed/utils/nvtx.py:15 in   │
│ wrapped_fn                                                                   │
│                                                                              │
│   12 │                                                                       │
│   13 │   def wrapped_fn(*args, **kwargs):                                    │
│   14 │   │   get_accelerator().range_push(func.__qualname__)                 │
│ ❱ 15 │   │   ret_val = func(*args, **kwargs)                                 │
│   16 │   │   get_accelerator().range_pop()                                   │
│   17 │   │   return ret_val                                                  │
│   18                                                                         │
│                                                                              │
│ /root/miniconda3/lib/python3.8/site-packages/deepspeed/runtime/engine.py:173 │
│ 5 in forward                                                                 │
│                                                                              │
│   1732 │   │   if self.fp16_auto_cast():                                     │
│   1733 │   │   │   inputs = self._cast_inputs_half(inputs)                   │
│   1734 │   │                                                                 │
│ ❱ 1735 │   │   loss = self.module(*inputs, **kwargs)                         │
│   1736 │   │                                                                 │
│   1737 │   │   if self.zero_optimization_partition_weights():                │
│   1738 │   │   │   # Disable automated discovery of external parameters      │
│                                                                              │
│ /root/miniconda3/lib/python3.8/site-packages/torch/nn/modules/module.py:1110 │
│ in _call_impl                                                                │
│                                                                              │
│   1107 │   │   # this function, and just call forward.                       │
│   1108 │   │   if not (self._backward_hooks or self._forward_hooks or self._ │
│   1109 │   │   │   │   or _global_forward_hooks or _global_forward_pre_hooks │
│ ❱ 1110 │   │   │   return forward_call(*input, **kwargs)                     │
│   1111 │   │   # Do not call functions when jit is used                      │
│   1112 │   │   full_backward_hooks, non_full_backward_hooks = [], []         │
│   1113 │   │   if self._backward_hooks or _global_backward_hooks:            │
│                                                                              │
│ /root/miniconda3/lib/python3.8/site-packages/lightning/pytorch/overrides/bas │
│ e.py:90 in forward                                                           │
│                                                                              │
│    87 │   │                                                                  │
│    88 │   │   if trainer is not None:                                        │
│    89 │   │   │   if trainer.training:                                       │
│ ❱  90 │   │   │   │   output = self._forward_module.training_step(*inputs, * │
│    91 │   │   │   │   # In manual_optimization, we need to prevent DDP reduc │
│    92 │   │   │   │   # it is done manually in `LightningModule.manual_backw │
│    93 │   │   │   │   # `require_backward_grad_sync` will be reset in the    │
│                                                                              │
│ /root/miniconda3/lib/python3.8/site-packages/deep_training/nlp/models/transf │
│ ormer_base.py:552 in training_step                                           │
│                                                                              │
│   549 │                                                                      │
│   550 │   def training_step(self, batch):                                    │
│   551 │   │   if isinstance(batch, dict):                                    │
│ ❱ 552 │   │   │   outputs = self.compute_loss(**batch)                       │
│   553 │   │   else:                                                          │
│   554 │   │   │   outputs = self.compute_loss(**dict(batch))                 │
│   555 │   │   loss = outputs[0]                                              │
│                                                                              │
│ /root/miniconda3/lib/python3.8/site-packages/deep_training/nlp/models/transf │
│ ormer_base.py:371 in compute_loss                                            │
│                                                                              │
│   368 │   def compute_loss(self, *args, **kwargs):                           │
│   369 │   │   if len(args):                                                  │
│   370 │   │   │   kwargs.update(dict(args))                                  │
│ ❱ 371 │   │   return self.model.compute_loss(**kwargs)                       │
│   372 │                                                                      │
│   373 │   def forward(self, *args, **kwargs):                                │
│   374 │   │   if len(args):                                                  │
│                                                                              │
│ /root/miniconda3/lib/python3.8/site-packages/deep_training/nlp/models/transf │
│ ormer_base.py:117 in compute_loss                                            │
│                                                                              │
│   114 │   │   return self.model(*args, **batch)                              │
│   115 │                                                                      │
│   116 │   def compute_loss(self, *args, **batch) -> tuple:                   │
│ ❱ 117 │   │   return self.model(*args, **batch)                              │
│   118 │                                                                      │
│   119 │   def post_init(self):                                               │
│   120 │   │   return self.model.post_init()                                  │
│                                                                              │
│ /root/miniconda3/lib/python3.8/site-packages/torch/nn/modules/module.py:1110 │
│ in _call_impl                                                                │
│                                                                              │
│   1107 │   │   # this function, and just call forward.                       │
│   1108 │   │   if not (self._backward_hooks or self._forward_hooks or self._ │
│   1109 │   │   │   │   or _global_forward_hooks or _global_forward_pre_hooks │
│ ❱ 1110 │   │   │   return forward_call(*input, **kwargs)                     │
│   1111 │   │   # Do not call functions when jit is used                      │
│   1112 │   │   full_backward_hooks, non_full_backward_hooks = [], []         │
│   1113 │   │   if self._backward_hooks or _global_backward_hooks:            │
│                                                                              │
│ /root/miniconda3/lib/python3.8/site-packages/accelerate/hooks.py:165 in      │
│ new_forward                                                                  │
│                                                                              │
│   162 │   │   │   with torch.no_grad():                                      │
│   163 │   │   │   │   output = old_forward(*args, **kwargs)                  │
│   164 │   │   else:                                                          │
│ ❱ 165 │   │   │   output = old_forward(*args, **kwargs)                      │
│   166 │   │   return module._hf_hook.post_forward(module, output)            │
│   167 │                                                                      │
│   168 │   module.forward = new_forward                                       │
│                                                                              │
│ /root/miniconda3/lib/python3.8/site-packages/deep_training/nlp/models/chatgl │
│ m2/modeling_chatglm.py:952 in forward                                        │
│                                                                              │
│    949 │   │   use_cache = use_cache if use_cache is not None else self.conf │
│    950 │   │   return_dict = return_dict if return_dict is not None else sel │
│    951 │   │                                                                 │
│ ❱  952 │   │   transformer_outputs = self.transformer(                       │
│    953 │   │   │   input_ids=input_ids,                                      │
│    954 │   │   │   position_ids=position_ids,                                │
│    955 │   │   │   attention_mask=attention_mask,                            │
│                                                                              │
│ /root/miniconda3/lib/python3.8/site-packages/torch/nn/modules/module.py:1110 │
│ in _call_impl                                                                │
│                                                                              │
│   1107 │   │   # this function, and just call forward.                       │
│   1108 │   │   if not (self._backward_hooks or self._forward_hooks or self._ │
│   1109 │   │   │   │   or _global_forward_hooks or _global_forward_pre_hooks │
│ ❱ 1110 │   │   │   return forward_call(*input, **kwargs)                     │
│   1111 │   │   # Do not call functions when jit is used                      │
│   1112 │   │   full_backward_hooks, non_full_backward_hooks = [], []         │
│   1113 │   │   if self._backward_hooks or _global_backward_hooks:            │
│                                                                              │
│ /root/miniconda3/lib/python3.8/site-packages/accelerate/hooks.py:165 in      │
│ new_forward                                                                  │
│                                                                              │
│   162 │   │   │   with torch.no_grad():                                      │
│   163 │   │   │   │   output = old_forward(*args, **kwargs)                  │
│   164 │   │   else:                                                          │
│ ❱ 165 │   │   │   output = old_forward(*args, **kwargs)                      │
│   166 │   │   return module._hf_hook.post_forward(module, output)            │
│   167 │                                                                      │
│   168 │   module.forward = new_forward                                       │
│                                                                              │
│ /root/miniconda3/lib/python3.8/site-packages/deep_training/nlp/models/chatgl │
│ m2/modeling_chatglm.py:826 in forward                                        │
│                                                                              │
│    823 │   │   batch_size, seq_length = input_ids.shape                      │
│    824 │   │                                                                 │
│    825 │   │   if inputs_embeds is None:                                     │
│ ❱  826 │   │   │   inputs_embeds = self.embedding(input_ids)                 │
│    827 │   │                                                                 │
│    828 │   │   if self.pre_seq_len is not None:                              │
│    829 │   │   │   if past_key_values is None:                               │
│                                                                              │
│ /root/miniconda3/lib/python3.8/site-packages/torch/nn/modules/module.py:1110 │
│ in _call_impl                                                                │
│                                                                              │
│   1107 │   │   # this function, and just call forward.                       │
│   1108 │   │   if not (self._backward_hooks or self._forward_hooks or self._ │
│   1109 │   │   │   │   or _global_forward_hooks or _global_forward_pre_hooks │
│ ❱ 1110 │   │   │   return forward_call(*input, **kwargs)                     │
│   1111 │   │   # Do not call functions when jit is used                      │
│   1112 │   │   full_backward_hooks, non_full_backward_hooks = [], []         │
│   1113 │   │   if self._backward_hooks or _global_backward_hooks:            │
│                                                                              │
│ /root/miniconda3/lib/python3.8/site-packages/accelerate/hooks.py:165 in      │
│ new_forward                                                                  │
│                                                                              │
│   162 │   │   │   with torch.no_grad():                                      │
│   163 │   │   │   │   output = old_forward(*args, **kwargs)                  │
│   164 │   │   else:                                                          │
│ ❱ 165 │   │   │   output = old_forward(*args, **kwargs)                      │
│   166 │   │   return module._hf_hook.post_forward(module, output)            │
│   167 │                                                                      │
│   168 │   module.forward = new_forward                                       │
│                                                                              │
│ /root/miniconda3/lib/python3.8/site-packages/deep_training/nlp/models/chatgl │
│ m2/modeling_chatglm.py:731 in forward                                        │
│                                                                              │
│    728 │                                                                     │
│    729 │   def forward(self, input_ids):                                     │
│    730 │   │   # Embeddings.                                                 │
│ ❱  731 │   │   words_embeddings = self.word_embeddings(input_ids)            │
│    732 │   │   embeddings = words_embeddings                                 │
│    733 │   │   # Data format change to avoid explicit tranposes : [b s h] -- │
│    734 │   │   embeddings = embeddings.transpose(0, 1).contiguous()          │
│                                                                              │
│ /root/miniconda3/lib/python3.8/site-packages/torch/nn/modules/module.py:1128 │
│ in _call_impl                                                                │
│                                                                              │
│   1125 │   │   │   bw_hook = hooks.BackwardHook(self, full_backward_hooks)   │
│   1126 │   │   │   input = bw_hook.setup_input_hook(input)                   │
│   1127 │   │                                                                 │
│ ❱ 1128 │   │   result = forward_call(*input, **kwargs)                       │
│   1129 │   │   if _global_forward_hooks or self._forward_hooks:              │
│   1130 │   │   │   for hook in (*_global_forward_hooks.values(), *self._forw │
│   1131 │   │   │   │   hook_result = hook(self, input, result)               │
│                                                                              │
│ /root/miniconda3/lib/python3.8/site-packages/accelerate/hooks.py:165 in      │
│ new_forward                                                                  │
│                                                                              │
│   162 │   │   │   with torch.no_grad():                                      │
│   163 │   │   │   │   output = old_forward(*args, **kwargs)                  │
│   164 │   │   else:                                                          │
│ ❱ 165 │   │   │   output = old_forward(*args, **kwargs)                      │
│   166 │   │   return module._hf_hook.post_forward(module, output)            │
│   167 │                                                                      │
│   168 │   module.forward = new_forward                                       │
│                                                                              │
│ /root/miniconda3/lib/python3.8/site-packages/torch/nn/modules/sparse.py:158  │
│ in forward                                                                   │
│                                                                              │
│   155 │   │   │   │   self.weight[self.padding_idx].fill_(0)                 │
│   156 │                                                                      │
│   157 │   def forward(self, input: Tensor) -> Tensor:                        │
│ ❱ 158 │   │   return F.embedding(                                            │
│   159 │   │   │   input, self.weight, self.padding_idx, self.max_norm,       │
│   160 │   │   │   self.norm_type, self.scale_grad_by_freq, self.sparse)      │
│   161                                                                        │
│                                                                              │
│ /root/miniconda3/lib/python3.8/site-packages/torch/nn/functional.py:2183 in  │
│ embedding                                                                    │
│                                                                              │
│   2180 │   │   #   torch.embedding_renorm_                                   │
│   2181 │   │   # remove once script supports set_grad_enabled                │
│   2182 │   │   _no_grad_embedding_renorm_(weight, input, max_norm, norm_type │
│ ❱ 2183 │   return torch.embedding(weight, input, padding_idx, scale_grad_by_ │
│   2184                                                                       │
│   2185                                                                       │
│   2186 def embedding_bag(                                                    │
╰──────────────────────────────────────────────────────────────────────────────╯
RuntimeError: Expected all tensors to be on the same device, but found at least 
two devices, cuda:3 and cuda:2! (when checking argument for argument index in 
method wrapper__index_select)
Exception ignored in: <function tqdm.__del__ at 0x7f679d8e63a0>
Traceback (most recent call last):
  File "/root/miniconda3/lib/python3.8/site-packages/tqdm/std.py", line 1152, in __del__
  File "/root/miniconda3/lib/python3.8/site-packages/tqdm/std.py", line 1306, in close
  File "/root/miniconda3/lib/python3.8/site-packages/tqdm/std.py", line 1499, in display
  File "/root/miniconda3/lib/python3.8/site-packages/tqdm/std.py", line 1155, in __str__
  File "/root/miniconda3/lib/python3.8/site-packages/tqdm/std.py", line 1457, in format_dict
TypeError: cannot unpack non-iterable NoneType object

**Comment by tjulh** [comment]
以上，麻烦作者大大看看

**Comment by ssbuild** [comment]
有2个解决方案参考下：
例如8卡 想使用 4,5,6,7, 
1. 设置 train_info_args['devices'] = [0,1,2,3].
设置环境变量 CUDA_VISIBLE_DEVICES=4,5,6,7

2. 设置 train_info_args['devices'] = 4.
设置环境变量 CUDA_VISIBLE_DEVICES=4,5,6,7

**Comment by tjulh** [comment]
> 有2个解决方案参考下： 例如8卡 想使用 4,5,6,7,
> 
>     1. 设置 train_info_args['devices'] = [0,1,2,3].
>        设置环境变量 CUDA_VISIBLE_DEVICES=4,5,6,7
> 
>     2. 设置 train_info_args['devices'] = 4.
>        设置环境变量 CUDA_VISIBLE_DEVICES=4,5,6,7

可以了，多谢作者
