### ISSUE TITLE
能否把训练的lora权重保存为 peft 支持的权重格式？

### ISSUE THREAD

**Issue by 506610466** [ssbuild/chatglm2_finetuning#25]
您好，
在使用当中，训练得到lora权重与项目耦合性太强，不能被huggingface的 peft 库加载，使用具有不便性。
能否把训练的lora权重保存为 peft 支持的权重格式？

**Comment by ssbuild** [comment]
https://github.com/ssbuild/chatglm2_finetuning/blob/dev/convert_lora_to_peft.py

**Comment by 506610466** [comment]
> https://github.com/ssbuild/chatglm2_finetuning/blob/dev/convert_lora_to_peft.py 参考这个脚本， 权重可以，lora配置文件配置，自行参照修改

测试的一下，生成的配置文件和 使用peft的配置文件不同，且即使修改后，使用peft加载模型成功，加载成功的模型是一个糟糕的模型，问什么问题都是胡说，  和使用你框架加载的模型根本不是同一个模型

**Comment by ssbuild** [comment]
感谢反馈，新脚本已测试通过，可以试试。

**Comment by 506610466** [comment]
> 感谢反馈，新脚本已测试通过，可以试试。

好了，可以使用！
