### ISSUE TITLE
能否支持一下在已训练的lora权重的基础上 继续 训练

### ISSUE THREAD

**Issue by shell-nlp** [ssbuild/chatglm2_finetuning#27]
能否支持一下在已训练的lora权重的基础上 继续 训练， 可以选择 从 base model 基础上开始 train ,或者 从lora 模型基础上开始 train

**Comment by ssbuild** [comment]
https://github.com/ssbuild/chatglm2_finetuning/blob/0f17dba3c31fa21ee3c5431c3daf48efd6dec10a/train.py#L99

放开注释，选择自己lora可以满足你这个需求。
