### ISSUE TITLE
关于数据  labels标签 的 -100填充

### ISSUE THREAD

**Issue by shell-nlp** [ssbuild/chatglm2_finetuning#29]
对数据进行padding时，默认是把labels的 instruction 给mask掉， 但是有时候，不需要把instruction 给mask为-100，即instruction  也参与计算loss. 是否可以支持

**Comment by ssbuild** [comment]
https://github.com/ssbuild/chatglm2_finetuning/blob/c9e3c9f2a9ef56b7498f178a0ee718bd0b6e6229/data_utils.py#L22
建议 sub  改成False, 或者根据自己的需求， 增加一个自定义的 DataStrategy 。
