### ISSUE TITLE
同时开启lora和量化之后报错

### ISSUE THREAD

**Issue by troycjj** [ssbuild/chatglm2_finetuning#6]
RuntimeError: Expected is_sm80 to be true, but got false.  (Could this error message be improved?  If so, please report an enhancement request to PyTorch.)

enable_deepspeed = False
enable_ptv2 = False
enable_lora = True
enable_int8 = False # qlora int8
enable_int4 = True # qlora int4

![image](https://github.com/ssbuild/chatglm2_finetuning/assets/52953954/9da01aed-37a6-43f9-a9ff-cbc22de30eaa)

![image](https://github.com/ssbuild/chatglm2_finetuning/assets/52953954/722d233f-fdfc-426c-8a4f-6ac87d6ae365)

配置：A5000 24G

**Comment by ssbuild** [comment]
torch 什么版本， 试试升级torch 到最新版本。

**Comment by troycjj** [comment]
> torch 什么版本， 试试升级torch 到最新版本。

2.2.0+cu118

**Comment by ssbuild** [comment]
不知道你从哪装的torch, 官方稳定版本好像是2.0.1

**Comment by troycjj** [comment]
> 不知道你从哪装的torch, 官方稳定版本好像是2.0.1

非常感谢，刚刚打错了，从2.0.0升级到2.0.1可以训练了，但是4bit量化也吃了18G显存，这是否不太合理？
